### ISSUE TITLE
bug: No "Bio" truncation in some mentors' profiles but the "Show more/less" button is still visible

### ISSUE THREAD

**Issue by khairahscorner** [WomenWhoCode/london#171]
### Describe the bug
For each mentor's card, the **"Bio"** section under the **"Presentation"** tab is expected to **not show** the **"Show More/Show Less"** button if the mentor's bio is not long enough for truncation. This works for some profiles but not for the one shown in Screenshots (and possibly others):

### To Reproduce
1. Go to `Mentors` section
2. Search for mentor with `Claudia`
3. See error

### Expected behavior
The "Show More/Show Less" button should not be visible for this mentor  since their `Bio` is not truncated.

### Screenshots
<img width="1204" alt="Screenshot 2023-10-25 at 10 57 09 am" src="https://github.com/WomenWhoCode/london/assets/38109438/d41e29e5-8f11-46a9-95f8-0b9b64a9f8b2">

<img width="1204" alt="Screenshot 2023-10-25 at 10 57 14 am" src="https://github.com/WomenWhoCode/london/assets/38109438/c064836c-e5ee-442f-a0f1-9bd40102213e">

### Reproducibility
- [x] The bug is reproducible consistently.
- [ ] The bug is sporadic or occurs randomly.

### Impact
- [ ] The bug affects critical functionality.
- [ ] The bug affects minor functionality.
- [x] The bug is a cosmetic issue.

### Proposed Solution (optional)
If you have any ideas on how to fix the bug or potential areas to investigate, suggest them here.

### Your Contribution (optional)
If you're able and willing to contribute a fix, mention it here.

**Comment by nora-weisser** [comment]
Hi @khairahscorner , I think this bug has been fixed, right? If yes, we can close it 😊

**Comment by khairahscorner** [comment]
Oh no, it's not yet fixed @nora-weisser. The fixed bug was another one with search returning incorrect number of profiles.

I haven't found a fix for what's causing this one.

**Comment by nora-weisser** [comment]
hmm..but it is not reproducible on the website right now 🧐:
<img width="1149" alt="Screenshot 2024-02-23 at 21 08 15" src="https://github.com/WomenWhoCode/london/assets/65826199/adb7e3b7-7754-4ed5-b710-eafcc69f672b">

**Comment by khairahscorner** [comment]
Just checked, it's because new mentors have been added. Now it's happening with "Lidiane Mayra Taquehara"

And the other bug seems to be back too🤔 Will have a look again

**Comment by nora-weisser** [comment]
ohh, I see, it seems weird 🙈 at this point, I am very curious what is causing these problems. I have one idea, what you can check (if that might be a reason) - mentor's data and indexing particularly. Currently, it is not very much consistent.

**Comment by khairahscorner** [comment]
Yeah, that was what brought the search bug back. Just made a PR to fix it: https://github.com/WomenWhoCode/london/pull/240

**Comment by nora-weisser** [comment]
I see, thanks for checking! 
I was done that way originally, because we wanted to make sure that number of index and number in the title of the picture match. Anyway, @IdayatSanni  will go through the whole list in the next PR soon and will make sure that everything is in order.
